### ISSUE TITLE
Can't install in python 3.5

### ISSUE THREAD

**Issue by dgahle** [cherab/openadas#41]
Getting this error when I try to install on python 3.5.

Installing adf15/pec96#he/pec96#he_pju#he0.dat...
Installing adf15/pec96#he/pec96#he_pju#he1.dat...
Installing adf15/pec96#be/pec96#be_pju#be0.dat...
Installing adf15/pec96#be/pec96#be_pju#be1.dat...
Installing adf15/pec96#be/pec96#be_pju#be2.dat...
Installing adf15/pec96#be/pec96#be_pju#be3.dat...
Installing adf15/pec96#c/pec96#c_vsu#c0.dat...
Installing adf15/pec96#c/pec96#c_vsu#c1.dat...
Installing adf15/pec96#c/pec96#c_vsu#c2.dat...
Installing adf15/pec96#n/pec96#n_vsu#n0.dat...
Installing adf15/pec96#n/pec96#n_vsu#n1.dat...
Installing adf11/acd12/acd12_h.dat...
Traceback (most recent call last):
  File "setup.py", line 101, in <module>
    repository.populate()
  File "/home/dgahle/cherab/openadas/cherab/openadas/repository/create.py", line 382, in populate
    install_files(rates, download=download, repository_path=repository_path, adas_path=adas_path)
  File "/home/dgahle/cherab/openadas/cherab/openadas/install.py", line 41, in install_files
    install_adf11acd(*args, download=download, repository_path=repository_path, adas_path=adas_path)
  File "/home/dgahle/cherab/openadas/cherab/openadas/install.py", line 118, in install_adf11acd
    repository.update_recombination_rates(rate_cherab, repository_path)
  File "/home/dgahle/cherab/openadas/cherab/openadas/repository/atomic.py", line 108, in update_recombination_rates
    _update_and_write_adf11(species, rate_data, path)
  File "/home/dgahle/cherab/openadas/cherab/openadas/repository/atomic.py", line 202, in _update_and_write_adf11
    json.dump(content, f, indent=2, sort_keys=True)
  File "/usr/local/depot/Python-3.5.1/lib/python3.5/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/usr/local/depot/Python-3.5.1/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/depot/Python-3.5.1/lib/python3.5/json/encoder.py", line 352, in _iterencode_dict
    items = sorted(dct.items(), key=lambda kv: kv[0])
TypeError: unorderable types: str() < int()

**Comment by mattngc** [comment]
I've just tested this with a fresh install and it all works fine. I suspect its a state issue from an older installation. Purging the atomic data and re-installing clean seems to work as expected.
