### ISSUE TITLE
Pip and manual installation fail

### ISSUE THREAD

**Issue by sballin** [cherab/openadas#9]
I've been having trouble installing this package on a cluster with `pip3 install --user` or with `python3 setup.py install` on v1.0.1 and its parents in the commit history. Here is my setup:

```
python==3.6.5
cython==0.29.2
numpy==1.16.0
cherab.core==1.0.1
raysect==0.5.4
scipy==1.2.0
matplotlib==3.0.5
pip==9.0.1 (also tried with 18.1)

PYTHONPATH=$HOME/.local/lib/python3.6/site-packages/
```

I get the following output:

```
    Complete output from command python setup.py egg_info:

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # CONDITIONS OF ANY KIND, either express or implied.
    #
    # See the Licence for the specific language governing permissions and limitations
    # under the Licence.

    from cherab.core cimport ImpactExcitationRate as CoreImpactExcitationRate
    ^
    ------------------------------------------------------------

    cherab/openadas/rates/pec.pxd:19:0: 'cherab/core.pxd' not found

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # CONDITIONS OF ANY KIND, either express or implied.
    #
    # See the Licence for the specific language governing permissions and limitations
    # under the Licence.

    from cherab.core cimport ImpactExcitationRate as CoreImpactExcitationRate
    ^
    ------------------------------------------------------------

    cherab/openadas/rates/pec.pxd:19:0: 'cherab/core/ImpactExcitationRate.pxd' not found

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    #
    # See the Licence for the specific language governing permissions and limitations
    # under the Licence.

    from cherab.core cimport ImpactExcitationRate as CoreImpactExcitationRate
    from cherab.core cimport RecombinationRate as CoreRecombinationRate
    ^
    ------------------------------------------------------------

    cherab/openadas/rates/pec.pxd:20:0: 'cherab/core/RecombinationRate.pxd' not found

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # See the Licence for the specific language governing permissions and limitations
    # under the Licence.

    from cherab.core cimport ImpactExcitationRate as CoreImpactExcitationRate
    from cherab.core cimport RecombinationRate as CoreRecombinationRate
    from cherab.core cimport ThermalCXRate as CoreThermalCXRate
    ^
    ------------------------------------------------------------

    cherab/openadas/rates/pec.pxd:21:0: 'cherab/core/ThermalCXRate.pxd' not found

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # under the Licence.

    from cherab.core cimport ImpactExcitationRate as CoreImpactExcitationRate
    from cherab.core cimport RecombinationRate as CoreRecombinationRate
    from cherab.core cimport ThermalCXRate as CoreThermalCXRate
    from cherab.core.math cimport Interpolate2DCubic
    ^
    ------------------------------------------------------------

    cherab/openadas/rates/pec.pxd:22:0: 'cherab/core/math.pxd' not found

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # under the Licence.

    from cherab.core cimport ImpactExcitationRate as CoreImpactExcitationRate
    from cherab.core cimport RecombinationRate as CoreRecombinationRate
    from cherab.core cimport ThermalCXRate as CoreThermalCXRate
    from cherab.core.math cimport Interpolate2DCubic
    ^
    ------------------------------------------------------------

    cherab/openadas/rates/pec.pxd:22:0: 'cherab/core/math/Interpolate2DCubic.pxd' not found

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from cherab.core cimport RecombinationRate as CoreRecombinationRate
    from cherab.core cimport ThermalCXRate as CoreThermalCXRate
    from cherab.core.math cimport Interpolate2DCubic


    cdef class ImpactExcitationRate(CoreImpactExcitationRate):
                                   ^
    ------------------------------------------------------------

    cherab/openadas/rates/pec.pxd:25:32: First base of 'ImpactExcitationRate' is not an extension type

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

        cdef:
            readonly dict raw_data
            readonly double wavelength
            readonly tuple density_range, temperature_range
            Interpolate2DCubic _rate
           ^
    ------------------------------------------------------------

    cherab/openadas/rates/pec.pxd:31:8: 'Interpolate2DCubic' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            readonly double wavelength
            readonly tuple density_range, temperature_range
            Interpolate2DCubic _rate


    cdef class RecombinationRate(CoreRecombinationRate):
                                ^
    ------------------------------------------------------------

    cherab/openadas/rates/pec.pxd:34:29: First base of 'RecombinationRate' is not an extension type

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

        cdef:
            readonly dict raw_data
            readonly double wavelength
            readonly tuple density_range, temperature_range
            Interpolate2DCubic _rate
           ^
    ------------------------------------------------------------

    cherab/openadas/rates/pec.pxd:40:8: 'Interpolate2DCubic' is not a type identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import matplotlib.pyplot as plt

    from cherab.core.utility.conversion import PhotonToJ


    cdef class ImpactExcitationRate(CoreImpactExcitationRate):
                                   ^
    ------------------------------------------------------------

    cherab/openadas/rates/pec.pyx:26:32: First base of 'ImpactExcitationRate' is not an extension type

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            # interpolate rate
            self._rate = Interpolate2DCubic(
                ne, te, rate, extrapolate=extrapolate, extrapolation_type="quadratic"
            )

        cpdef double evaluate(self, double density, double temperature) except? -1e999:
             ^
    ------------------------------------------------------------

    cherab/openadas/rates/pec.pyx:55:10: C method 'evaluate' not previously declared in definition part of extension type 'ImpactExcitationRate'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

            # prevent -ve values (possible if extrapolation enabled)
            return max(0, self._rate.evaluate(density, temperature))


    cdef class RecombinationRate(CoreRecombinationRate):
                                ^
    ------------------------------------------------------------

    cherab/openadas/rates/pec.pyx:61:29: First base of 'RecombinationRate' is not an extension type

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            self._rate = Interpolate2DCubic(
                ne, te, rate, extrapolate=extrapolate, extrapolation_type="quadratic"
            )


        cpdef double evaluate(self, double density, double temperature) except? -1e999:
             ^
    ------------------------------------------------------------

    cherab/openadas/rates/pec.pyx:91:10: C method 'evaluate' not previously declared in definition part of extension type 'RecombinationRate'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            # store limits of data
            self.density_range = ne.min(), ne.max()
            self.temperature_range = te.min(), te.max()

            # interpolate rate
            self._rate = Interpolate2DCubic(
                        ^
    ------------------------------------------------------------

    cherab/openadas/rates/pec.pyx:51:21: 'Interpolate2DCubic' is not a constant, variable or function identifier

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            # store limits of data
            self.density_range = ne.min(), ne.max()
            self.temperature_range = te.min(), te.max()

            # interpolate rate
            self._rate = Interpolate2DCubic(
                        ^
    ------------------------------------------------------------

    cherab/openadas/rates/pec.pyx:86:21: 'Interpolate2DCubic' is not a constant, variable or function identifier
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0ey5jop_/cherab-openadas/setup.py", line 47, in <module>
        extensions = cythonize(extensions, nthreads=multiprocessing.cpu_count(), force=force, compiler_directives=cython_directives)
      File "/home/gridsan/sballinger/.local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1097, in cythonize
        cythonize_one(*args)
      File "/home/gridsan/sballinger/.local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1220, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: cherab/openadas/rates/pec.pyx
    Compiling cherab/openadas/rates/pec.pyx because it depends on /home/gridsan/sballinger/.local/lib/python3.6/site-packages/Cython/Includes/numpy/__init__.pxd.
    [1/1] Cythonizing cherab/openadas/rates/pec.pyx

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-0ey5jop_/cherab-openadas/
```

**Comment by mattngc** [comment]
Hi @sballin,

Apologies you've been waiting so long for a reply. Somehow I didn't have notifications turned on for this repository, so I didn't see your issue when it was posted. Only just noticed. I'll have a think about this and get back to you later today.

Matt

**Comment by mattngc** [comment]
Hi @sballin,

I think something has gone wrong with the core installation as the open-adas package can't find the necessary header files in your python module paths. I suggest you start again clean.

First, have you checked Raysect is working by running a demo script from Raysect?

The easiest way to install CHERAB is from PyPi through pip. I have just re-written some of the documentation pages on this:
https://cherab.github.io/documentation/installation_and_structure.html#installing-through-pip

But essentially, you just want this command:
`pip install cherab cherab-openadas --user`

Let us know how you go.

**Comment by sballin** [comment]
No worries, I think your advice is correct. I got this working a while ago, so I should have closed this issue but forgot. One thing that was important was to add the `--no-cache` flag to pip when installing raysect and cherab, which fixed the following error, in case others run into it:

```
>>> import cherab.core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sballinger/.local/lib/python3.6/site-packages/cherab/core/__init__.py", line 20, in <module>
    from .atomic import *
  File "/home/sballinger/.local/lib/python3.6/site-packages/cherab/core/atomic/__init__.py", line 22, in <module>
    from .interface import AtomicData
  File "cherab/core/atomic/rates.pxd", line 22, in init cherab.core.atomic.interface
ImportError: /home/sballinger/.local/lib/python3.6/site-packages/cherab/core/atomic/rates.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _intel_fast_memcmp
```

**Comment by mattngc** [comment]
Excellent, thanks Sean. Let us know if you need help with anything else. I'm doing a documentation blitz at the moment so that should help :)

**Comment by drsmith48** [comment]
I received the same 'not found' errors during the cython compile using both `pip install cherab-openadas` and `python setup.py install`.  The pip flag --no-cache(-dir) did not resolve the error for me.  I did find the solution, though.  The docs for building cython packages note an incompatibility between zipped eggs (default build) and cimport for pdx files.  The solution is to add `zip_safe=False` in setup():
https://cython.readthedocs.io/en/latest/src/quickstart/build.html#building-a-cython-module-using-distutils
I cloned raysect, cherab, and cherab-openadas, and I added `zip_safe=False` in setup() in all setup.py files.  Now I can run `python setup.py install` for cherab-openadas without any problems.  By the way, thank you for the cherab package.

**Comment by CnlPepper** [comment]
Hi @drsmith48, thanks for using cherab and for your feedback! Would you be able to provide us with a little more detail about your environment? I've been unable to recreate this issue using Ubuntu 18.04 with the Anaconda python distribution. If possible could you tell us the OS, python version and cython versions you have available?

**Comment by CnlPepper** [comment]
I'll add the zip_safe=False setting and investigate further.

**Comment by mattngc** [comment]
Alex is more of the installation/distribution expert, so I'll let him handle this one.

**Comment by drsmith48** [comment]
Sure, I'm on MacOS 10.13 with Python 3.7.2 and Cython 0.29.5, both installed in a conda environment.

**Comment by CnlPepper** [comment]
Given, as you point out, it is recommended to add this flag, I've updated the setup.py in all the various packages. The fixes are in the development branches so will be rolled out with the next release (which should hopefully be relatively soon).

Thanks again :)
